spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/news?useSSL=false&characterEncoding=UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: debug